name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SOLUTION_NAME: GravityLib.sln
  PROJECTS: |
    GravityLib.Common/GravityLib.Common.csproj
    GravityLib.EntityFramework/GravityLib.EntityFramework.csproj
    GravityLib.Http/GravityLib.Http.csproj
  NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  VERSION: 1.0.${{ github.run_number }}
  NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-pack:
    runs-on: gha-runner-scale-set-linux

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}

    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_NAME }} --configuration Release -p:Version=${{ env.VERSION }} --no-restore

    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_NAME }} --no-restore --no-build

    - name: Pack and Publish
      run: |
        rm -rf ./packages
        mkdir ./packages
        for project in ${{ env.PROJECTS }}; do
          dotnet pack "$project" --configuration Release --no-restore --no-build -p:PackageVersion=${{ env.VERSION }} -o ./packages
        done
        dotnet nuget push ./packages/*.nupkg --source ${{ env.NUGET_SOURCE }} --api-key ${{ env.NUGET_API_KEY }} --skip-duplicate
